// <auto-generated />
using System;
using Finantial_Manager_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finantial_Manager_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511204720_FixingUserIdInModel")]
    partial class FixingUserIdInModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Finantial_Manager_API.Models.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlertThresholdPercenage")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("LimitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<bool>("RollsOver")
                        .HasColumnType("bit");

                    b.Property<decimal>("SpentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.BudgetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("CategoryLimit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BudgetCategories");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da7419ae-5a37-4023-8684-bbf7c132121e"),
                            Color = "#22C55E",
                            CreatedAt = new DateTime(2026, 5, 11, 20, 47, 19, 341, DateTimeKind.Utc).AddTicks(772),
                            Icon = "briefcase",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Salary",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("fec0e21f-7b35-41f4-a0f8-8c0af6916591"),
                            Color = "#3B82F6",
                            CreatedAt = new DateTime(2026, 5, 11, 20, 47, 19, 341, DateTimeKind.Utc).AddTicks(3991),
                            Icon = "laptop",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Freelance",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("3d195d65-6234-438b-8f3a-ea6179c3de2b"),
                            Color = "#F97316",
                            CreatedAt = new DateTime(2026, 5, 11, 20, 47, 19, 341, DateTimeKind.Utc).AddTicks(3998),
                            Icon = "utensils",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Food",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("1e924aab-5b90-4342-b9e1-92172f995cd3"),
                            Color = "#8B5CF6",
                            CreatedAt = new DateTime(2026, 5, 11, 20, 47, 19, 341, DateTimeKind.Utc).AddTicks(4001),
                            Icon = "car",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Transport",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("f768055e-0520-4515-ad3f-0ea2882b69b2"),
                            Color = "#EF4444",
                            CreatedAt = new DateTime(2026, 5, 11, 20, 47, 19, 341, DateTimeKind.Utc).AddTicks(4018),
                            Icon = "file-text",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Bills",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("39de397b-8f7d-406b-b21b-ce736cafb4e1"),
                            Color = "#EC4899",
                            CreatedAt = new DateTime(2026, 5, 11, 20, 47, 19, 341, DateTimeKind.Utc).AddTicks(4021),
                            Icon = "heart-pulse",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Health",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("4488a0d3-a34a-4669-aa39-6da8b273af36"),
                            Color = "#14B8A6",
                            CreatedAt = new DateTime(2026, 5, 11, 20, 47, 19, 341, DateTimeKind.Utc).AddTicks(4024),
                            Icon = "book-open",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Education",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("df1885e8-b393-4f26-a017-d8c91beed922"),
                            Color = "#F59E0B",
                            CreatedAt = new DateTime(2026, 5, 11, 20, 47, 19, 341, DateTimeKind.Utc).AddTicks(4027),
                            Icon = "gamepad-2",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Leisure",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriptionn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("RecurringInterval")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyPreference")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.Budget", b =>
                {
                    b.HasOne("Finantial_Manager_API.Models.User", "User")
                        .WithOne("Budget")
                        .HasForeignKey("Finantial_Manager_API.Models.Budget", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.BudgetCategory", b =>
                {
                    b.HasOne("Finantial_Manager_API.Models.Budget", "Budget")
                        .WithMany("BudgetCategories")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finantial_Manager_API.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.Category", b =>
                {
                    b.HasOne("Finantial_Manager_API.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Finantial_Manager_API.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.Transaction", b =>
                {
                    b.HasOne("Finantial_Manager_API.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finantial_Manager_API.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.Budget", b =>
                {
                    b.Navigation("BudgetCategories");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.Category", b =>
                {
                    b.Navigation("SubCategories");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.User", b =>
                {
                    b.Navigation("Budget");

                    b.Navigation("Categories");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
