// <auto-generated />
using System;
using Finantial_Manager_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finantial_Manager_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Finantial_Manager_API.Models.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlertThresholdPercenage")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("LimitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<bool>("RollsOver")
                        .HasColumnType("bit");

                    b.Property<decimal>("SpentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.BudgetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("CategoryLimit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BudgetCategories");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67c30f41-1692-470f-8e95-8b860ebc941b"),
                            Color = "#22C55E",
                            CreatedAt = new DateTime(2026, 5, 7, 20, 54, 10, 721, DateTimeKind.Utc).AddTicks(6624),
                            Icon = "briefcase",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Salary",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("537d5c4b-b4e2-48bc-a0da-a6773ee3afe2"),
                            Color = "#3B82F6",
                            CreatedAt = new DateTime(2026, 5, 7, 20, 54, 10, 721, DateTimeKind.Utc).AddTicks(9944),
                            Icon = "laptop",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Freelance",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("f1e84489-9df4-4d60-8cd6-ca2a8b2ae5f0"),
                            Color = "#F97316",
                            CreatedAt = new DateTime(2026, 5, 7, 20, 54, 10, 721, DateTimeKind.Utc).AddTicks(9950),
                            Icon = "utensils",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Food",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("ff811118-507c-4b8e-b6b9-bbefff2d9a48"),
                            Color = "#8B5CF6",
                            CreatedAt = new DateTime(2026, 5, 7, 20, 54, 10, 721, DateTimeKind.Utc).AddTicks(9954),
                            Icon = "car",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Transport",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("d2872953-de74-4c7a-8115-1bd457468596"),
                            Color = "#EF4444",
                            CreatedAt = new DateTime(2026, 5, 7, 20, 54, 10, 721, DateTimeKind.Utc).AddTicks(9956),
                            Icon = "file-text",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Bills",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("bdddbc13-a9f9-4f73-b97d-280ef80ac14b"),
                            Color = "#EC4899",
                            CreatedAt = new DateTime(2026, 5, 7, 20, 54, 10, 721, DateTimeKind.Utc).AddTicks(9965),
                            Icon = "heart-pulse",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Health",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("a58774f2-22e6-4dfb-948f-f7eaf4451f81"),
                            Color = "#14B8A6",
                            CreatedAt = new DateTime(2026, 5, 7, 20, 54, 10, 721, DateTimeKind.Utc).AddTicks(9968),
                            Icon = "book-open",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Education",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("293c0022-db65-42f3-806e-416544ba4aea"),
                            Color = "#F59E0B",
                            CreatedAt = new DateTime(2026, 5, 7, 20, 54, 10, 721, DateTimeKind.Utc).AddTicks(9971),
                            Icon = "gamepad-2",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Leisure",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriptionn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("RecurringInterval")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.User", b =>
                {
                    b.Property<Guid>("Ind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyPreference")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Ind");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.Budget", b =>
                {
                    b.HasOne("Finantial_Manager_API.Models.User", "User")
                        .WithOne("Budget")
                        .HasForeignKey("Finantial_Manager_API.Models.Budget", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.BudgetCategory", b =>
                {
                    b.HasOne("Finantial_Manager_API.Models.Budget", "Budget")
                        .WithMany("BudgetCategories")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finantial_Manager_API.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.Category", b =>
                {
                    b.HasOne("Finantial_Manager_API.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Finantial_Manager_API.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.Transaction", b =>
                {
                    b.HasOne("Finantial_Manager_API.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finantial_Manager_API.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.Budget", b =>
                {
                    b.Navigation("BudgetCategories");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.Category", b =>
                {
                    b.Navigation("SubCategories");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Finantial_Manager_API.Models.User", b =>
                {
                    b.Navigation("Budget");

                    b.Navigation("Categories");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
